/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pibic.logica;

import br.com.pibic.util.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Said
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() throws SQLException {
        initComponents();
        PopularCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldNomeProduto = new javax.swing.JTextField();
        TextFieldValorProduto = new javax.swing.JTextField();
        CadastrarProdutoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldQuantidadeProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldNivelReposicao = new javax.swing.JTextField();
        ComboBoxCategoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome:");

        jLabel2.setText("Valor:");

        TextFieldNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeProdutoActionPerformed(evt);
            }
        });

        CadastrarProdutoButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CadastrarProdutoButton.setText("Cadastrar");
        CadastrarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Cadastrar Produto");

        jLabel4.setText("Quantidade :");

        TextFieldQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldQuantidadeProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nivel de Reposição :");

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Categoria:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadastrarProdutoButton)
                            .addComponent(TextFieldNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(TextFieldValorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(TextFieldQuantidadeProduto)
                            .addComponent(TextFieldNivelReposicao)
                            .addComponent(ComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextFieldQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldNivelReposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastrarProdutoButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeProdutoActionPerformed

    private void CadastrarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoButtonActionPerformed
        // quando o botão for clicado,irá cadastrar o produto no banco de dados

        try { // try para caso houver erro
            Connection conn = Conexao.createConnection();  // pegamos a conexão com o banco de dados
            String NomeProduto = TextFieldNomeProduto.getText();
            String ValorProduto = TextFieldValorProduto.getText();
            String QuantidadeProduto = TextFieldQuantidadeProduto.getText();
            String NivelReposicao = TextFieldNivelReposicao.getText();
            String Categoria = ComboBoxCategoria.getSelectedItem().toString();

            if (!NomeProduto.isEmpty() && !ValorProduto.isEmpty() && !QuantidadeProduto.isEmpty() && !NivelReposicao.isEmpty() && !Categoria.isEmpty()) {
                String sqla = "Select id from categorias where nome = ?";
                PreparedStatement ps = conn.prepareStatement(sqla);
                ps.setString(1, Categoria);
                ResultSet resultado = ps.executeQuery();
                int id_categoria = -1;
                while (resultado.next()) {

                    id_categoria = resultado.getInt("id");
                }
                String sql = "INSERT INTO produtos(nome,valor,quantidade,nivelRepo,categoria_id) VALUES(?,?,?,?,?)"; // query para inserção

                ps = conn.prepareStatement(sql); // prepara a query para ser executada
                ps.setString(1, NomeProduto);
                ps.setFloat(2, Float.parseFloat(ValorProduto));
                ps.setInt(3, Integer.parseInt(QuantidadeProduto));
                ps.setInt(4, Integer.parseInt(NivelReposicao));
                ps.setInt(5, id_categoria);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Produto Cadastrado com Sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Produto!");

                }

                conn.close();
            } else {

                JOptionPane.showMessageDialog(null, "Preencha Todos os campos para cadastrar um produto !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        limparbotao();

    }//GEN-LAST:event_CadastrarProdutoButtonActionPerformed

    private void TextFieldQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldQuantidadeProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroProduto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void PopularCategoria() throws SQLException {
        List<String> ListaCategoria = new ArrayList<String>(); //lista pra armazenar os produtos lidos do bd
        Connection conexao = Conexao.createConnection(); // conexao

        String sql = "Select * from categorias"; // query
        PreparedStatement ps = conexao.prepareStatement(sql); // prepara a query

        ResultSet resultado = ps.executeQuery(); //realiza a consulta

        while (resultado.next()) {
            ListaCategoria.add(resultado.getString("nome")); // adiciona  o produto na lista
        }
        DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel(ListaCategoria.toArray()); // cria o modelo do combo
        ComboBoxCategoria.setModel(modeloComboBox); // adiciona o modelo ao comboBox
        conexao.close();
    }
    

    public void limparbotao() {
        TextFieldNivelReposicao.setText("");
        TextFieldNomeProduto.setText("");
        TextFieldQuantidadeProduto.setText("");
        TextFieldValorProduto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarProdutoButton;
    private javax.swing.JComboBox ComboBoxCategoria;
    private javax.swing.JTextField TextFieldNivelReposicao;
    private javax.swing.JTextField TextFieldNomeProduto;
    private javax.swing.JTextField TextFieldQuantidadeProduto;
    private javax.swing.JTextField TextFieldValorProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
