/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pibic.logica;

import br.com.pibic.util.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Said
 */
public class ConsultaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaEstoque
     */
    TableRowSorter filtro = null;

    public ConsultaEstoque() throws SQLException {
        initComponents();
        PopularTabela(); // popular tabela ao carregar a tela

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaConsultaProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TextFieldFiltro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabelaConsultaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(TabelaConsultaProdutos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Filtro:");

        TextFieldFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFiltroActionPerformed

        if (TextFieldFiltro.getText().length() == 0) {
            filtro.setRowFilter(null);
        } else {
            filtro.setRowFilter(RowFilter.regexFilter(TextFieldFiltro.getText()));
        }
    }//GEN-LAST:event_TextFieldFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConsultaEstoque().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ConsultaEstoque.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

    }

    void PopularTabela() throws SQLException // Função é chamada ao iniciar a tela,para preencher a tabela com os produtos do banco de dados
    {
        Connection conexao = Conexao.createConnection(); // cria ocnexão
        DefaultTableModel modelo = new DefaultTableModel(); // cria modelo para a tabela
        TabelaConsultaProdutos.setModel(modelo); // poi o modelo criado na tabela
        TabelaConsultaProdutos.setAutoCreateRowSorter(true);
 
        String sqli = "SELECT * FROM produtos p,categorias c where p.categoria_id = c.id";// query para consulta
        PreparedStatement ps = conexao.prepareStatement(sqli); // prepara a query
        modelo.addColumn("ID"); // ADICIONA a coluna id
        modelo.addColumn("PRODUTO"); // adiciona a coluna produto
        modelo.addColumn("VALOR"); // adiciona a coluna valor
        modelo.addColumn("QUANTIDADE");//adiciona a coluna quantidade          
        modelo.addColumn("CATEGORIA");// adiciona a coluna categoria
        modelo.addColumn("NIVEL REPOSIÇÃO");// adiciona a coluna reposicao,coloca o cedilha pq no meu not nao tem
        ResultSet resultado = ps.executeQuery();
        while (resultado.next()) // enquanto não chegar no fim do resultado
        {

            modelo.addRow(new Object[]{resultado.getString(1), resultado.getString(2), resultado.getString(3), resultado.getString(4), resultado.getString("nome"), resultado.getString(6)});
            // adiciona na linha o valor do id,que no caso é a primeira coluna,o produto,que é a segunda coluna,e a 3 que é a 3 coluna
            // quando criares quantidade,vai precisar adicionar ai também :)
        }
        filtro = new TableRowSorter<TableModel>(modelo);
        TabelaConsultaProdutos.setRowSorter(filtro);
        conexao.close();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaConsultaProdutos;
    private javax.swing.JTextField TextFieldFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
